name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:

    runs-on: ubuntu-latest
    env:
      name: 'rt'
      username: lseino

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        docker login --username=${{ secrets.DOCKERHUB_USERNAME }} --password=${{ secrets.DOCKERHUB_TOKEN }}
        docker build -t "$username/$name:v1.0" .
        docker push "$username/$name:v1.0"
        echo "image name for terraform task definition = $username/$name:v1.0"