name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:

    runs-on: ubuntu-latest
    env:
      name: 'python-app'

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        docker login --username=${{ secrets.DOCKERHUB_USERNAME }} --password= # ${{ secrets.DOCKERHUB_TOKEN }}
        docker build -t ${{ secrets.DOCKERHUB_TOKEN }}/$name:v1.0.0 .
        docker push ${{ secrets.DOCKERHUB_TOKEN }}/$name:v1.0.0
        echo "image name for terraform task definition = ${{ secrets.DOCKERHUB_TOKEN }}/$name:v1.0.0"